version: "3.9"
services:
  build:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: buildimage
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - build
    image: testimage
    